TEST_SOURCES =\
  Libraries/Quanta/Source/Math/Matrix4.cpp\
  Libraries/Quanta/Source/Math/Quaternion.cpp\
  Libraries/Quanta/Source/Math/Vector3.cpp\
  Libraries/Quanta/Source/Math/Vector4.cpp\
  Libraries/Quanta/Source/Geometry/Transform.cpp\
  Libraries/Quanta/Source/Geometry/TransformFactory3D.cpp\
  Libraries/Quanta/Source/Util.cpp\
  Libraries/Piper/Source/Util.cpp\
  Libraries/Piper/Source/AckSet128.cpp\
  Libraries/Piper/Source/AckSet32.cpp\
  Libraries/Fixie/Library/Source/Trig.cpp\
  Libraries/Fixie/Library/Source/Util.cpp\
  Libraries/Fixie/Library/Source/Vector2.cpp\
  Libraries/Fixie/Library/Source/Vector3.cpp\
  Libraries/Fixie/Library/Source/Matrix4.cpp\
  Libraries/Fixie/Library/Source/Quaternion.cpp\
  Misc/Error.cpp\
  Misc/IntegerPool.cpp\
  Misc/HandleList.cpp\
  Physics/Engine.cpp\
  Physics/CollisionResolver.cpp\
  Physics/Integrator.cpp\
  Physics/CollisionDetector.cpp\
  Physics/SphereColliderList.cpp\
  Physics/BodyList.cpp\
  Physics/DynamicDriverList.cpp\
  Physics/KinematicDriverList.cpp\
  Simulation/Pathfinding/AStarPriorityQueue.cpp\
  Simulation/Pathfinding/AStarCostMap.cpp\
  Simulation/Pathfinding/AStarCostBucket.cpp\
  Simulation/Pathfinding/Map.cpp\
  Simulation/Pathfinding/AStar.cpp\
  Simulation/Pathfinding/MapDirectionList.cpp\
  Simulation/Pathfinding/MapNeighbourIterator.cpp\
  Misc/LoopStream.cpp\
  Test/main.cpp
